# Generated by Django 3.0.3 on 2020-03-17 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csruby_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csruby_user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
    ]
