# Generated by Django 3.0.3 on 2020-03-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csruby_app', '0002_added_date_joined_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('COG', 'Consumer grade'), ('ING', 'Industrial grade'), ('MIS', 'Mil-spec'), ('RST', 'Restricted'), ('CLA', 'Classified'), ('COV', 'Covert'), ('EXR', 'Exceedingly Rare'), ('CON', 'Contraband'), ('RES', 'Remarkable Sticker'), ('HGS', 'High Grade Sticker'), ('EXS', 'Extraordinary Sticker'), ('EXG', 'Extraordinary Gloves'), ('CRT', 'Crate')], default='COG', max_length=3),
        ),
    ]
