# Generated by Django 3.0.3 on 2020-02-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csruby_app', '0002_auto_20200227_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('item_image', models.CharField(max_length=255)),
                ('rarity', models.CharField(choices=[('COG', 'Consumer grade'), ('ING', 'Industrial grade'), ('MIS', 'Mil-spec'), ('RES', 'Restricted'), ('CLA', 'Classified'), ('COV', 'Covert'), ('EXR', 'Exceedingly Rare'), ('CON', 'Contraband')], default='COG', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='email',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='User', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csruby_app.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Admin')], default=1),
        ),
    ]
