# Generated by Django 3.0.3 on 2020-02-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csruby_app', '0003_add_item_and_price_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_created_at', models.DateTimeField()),
                ('sell_created_at', models.DateTimeField()),
                ('buy_item', models.BooleanField(default=False)),
                ('sell_item', models.BooleanField(default=False)),
                ('favorite_item', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csruby_app.Item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csruby_app.User')),
            ],
        ),
    ]
