# Generated by Django 3.0.3 on 2020-03-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csruby_app', '0005_rename_barter_model_to_user_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='steamid',
            field=models.CharField(blank=True, default=None, max_length=17, null=True),
        ),
    ]
