# Generated by Django 3.0.3 on 2020-03-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csruby_app', '0006_steamid_can_be_null_and_email_uses_email_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
